create database GREENPLATE;

use GREENPLATE;

# 관리자, 유저, 회사, 라이브커머스, 라이브커머스키워드, 키워드, 유저키워드, 레시피, 키워드, 레시피

## DB 테이블 제작 ####################################################################
CREATE TABLE `ITEM` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `CATEGORY_ID` BIGINT NOT NULL,
    `COMPANY_ID` BIGINT NOT NULL,
    `NAME` varchar(30) NOT NULL,
    `EXPLAIN` varchar(3000) NULL,
    `PRICE` decimal(10,3) NOT NULL,
    `STOCK` BIGINT NOT NULL,
    `CALORIE` varchar(10) NULL,
    `IMAGE_URL1` varchar(300) NULL,
    `EXPIRATION_DATE` date NULL,
    `DEL_YN` tinyint(1) NULL DEFAULT 0,
    `CREATED_DATE` datetime NULL,
    `MODIFIED_DATE` datetime NULL,
    PRIMARY KEY (`ID`, `CATEGORY_ID`, `COMPANY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CATEGORY` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `CODE` VARCHAR(30) NOT NULL,
    `CODE_NAME` VARCHAR(30) NOT NULL,
    `DEL_YN` tinyint(1) NULL DEFAULT 0,
    `CREATED_DATE` datetime NULL,
    `MODIFIED_DATE` datetime NULL,
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MANAGER` (
	`ID`	BIGINT	NOT NULL AUTO_INCREMENT,
    `EMAIL`	varchar(100)	NOT NULL,
	`PW`	varchar(100)	NOT NULL,
	`NAME`	varchar(12)	NOT NULL,
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `COMPANY` (
	`ID`	BIGINT	NOT NULL AUTO_INCREMENT,
	`EMAIL`	varchar(100)	NOT NULL,
	`PW`	varchar(100)	NOT NULL,
	`BIZ_NAME`	varchar(30)	NOT NULL,
	`BIZ_NO`	varchar(30)	NOT NULL,
	`ADDRESS`	varchar(200)	NULL,
	`TEL`	varchar(12)	NULL,
	`DEL_YN`	tinyint(1)	NULL	DEFAULT 0,
	`CREATED_DATE`	datetime	NULL,
	`MODIFIED_DATE`	datetime	NULL,
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `LIVECOMMERCE` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `MANAGER_ID` BIGINT NOT NULL,
    `COMPANY_ID` BIGINT NOT NULL,
    `TITLE` varchar(30) NOT NULL,
    `DESCRIPTION` varchar(100) NULL,
    `LIVE_DATE` date NOT NULL,
    `START_TIME` datetime NOT NULL,
    `END_TIME` datetime NOT NULL,
    PRIMARY KEY (`ID`, `MANAGER_ID`, `COMPANY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `KEYWORD` ( 
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `KEYWORD_CODE` varchar(30) NOT NULL,
    `KEYWORD_NAME` varchar(30) NOT NULL,
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `LIVECOMMERCE_KEYWORD` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `KEYWORD_ID` BIGINT NOT NULL,
    `LIVECOMMERCE_ID` BIGINT NOT NULL,
    PRIMARY KEY (`ID`, `KEYWORD_ID`, `LIVECOMMERCE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `RECIPE` ( 
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USER_ID`	BIGINT	NOT NULL,
    `TITLE` varchar(30) NOT NULL,
    `CONTENTS` varchar(5000) NOT NULL,
    `NAME` varchar(30) NULL,
    `LIKES` BIGINT NULL,
    `DEL_YN` tinyint(1) NULL DEFAULT 0,
    `CREATED_DATE` datetime NULL,
    `MODIFIED_DATE` datetime NULL,
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `RECIPE_KEYWORD` ( 
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `KEYWORD_ID` BIGINT NOT NULL,
    `RECIPE_ID` BIGINT NOT NULL,
    PRIMARY KEY (`ID`, `KEYWORD_ID`, `RECIPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `USER` ( 
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `EMAIL` varchar(100) NOT NULL,
    `NAME` varchar(12) NOT NULL,
    `NICKNAME` varchar(30) NOT NULL,
    `BIRTHDAY` INT NULL,
    `PW` varchar(100) NOT NULL,
    `LOGIN_COUNT` INT NULL,
    `DEL_YN` tinyint(1) NULL DEFAULT 0,
    `CREATED_DATE` datetime NULL,
    `MODIFIED_DATE` datetime NULL,
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `USER_KEYWORD` ( 
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USER_ID` BIGINT NOT NULL,
    `KEYWORD_ID` BIGINT NOT NULL,
    PRIMARY KEY (`ID`, `USER_ID`, `KEYWORD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ORDERS` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USER_ID` BIGINT NOT NULL,
    `ADDRESS_ID` BIGINT NOT NULL,
    `ORDER_DATE` datetime NULL,
    `TOTAL_PRICE` decimal(10,3) NOT NULL,
    `TOTAL_CNT` INT NOT NULL,
    `ORDER_STATE` varchar(50) NOT NULL,
    `REFUND_YN` INT NOT NULL,
    `DEL_YN` tinyint(1) NULL DEFAULT 0,
    `CREATED_DATE` datetime NULL,
    `MODIFIED_DATE` datetime NULL,
    PRIMARY KEY (`ID`, `USER_ID`, `ADDRESS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ORDER_DETAILS` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `ORDERS_ID` BIGINT NOT NULL,
    `ITEM_ID` BIGINT NOT NULL,
    `CNT` INT NOT NULL,
    `PRICE` decimal(10,3) NOT NULL,
    `REFUND_YN` INT NOT NULL,
    `DEL_YN` tinyint(1) NULL DEFAULT 0,
    `CREATED_DATE` datetime NULL,
    `MODIFIED_DATE` datetime NULL,
    PRIMARY KEY (`ID`, `ORDERS_ID`, `ITEM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `REVIEW` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `RECIPE_ID` BIGINT NOT NULL,
    `USER_ID` BIGINT NOT NULL,
    `STAR_POINT` INT NOT NULL,
    `CONTENT` varchar(100) NULL,
    `IMAGE_URL` varchar(30) NOT NULL,
    PRIMARY KEY (`ID`, `RECIPE_ID`, `USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `RECIPE_ITEM` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `RECIPE_ID` BIGINT NOT NULL,
    `ITEM_ID` BIGINT NOT NULL,
    PRIMARY KEY (`ID`, `RECIPE_ID`, `ITEM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ADDRESS` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USER_ID` BIGINT NOT NULL,
    `ZIPCODE` INT NOT NULL,
    `ADDRESS` varchar(200) NOT NULL,
    `ADDRESS_DETAIL` varchar(100) NULL,
    `RECIPIENT` varchar(12) NOT NULL,
    `PHONE_NUM` INT NOT NULL,
    `DEFULT_ADDR` tinyint(1) NULL	DEFAULT 0,
    PRIMARY KEY (`ID`, `USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


ALTER TABLE `ITEM` ADD CONSTRAINT `FK_CATEGORY_TO_ITEM_1` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `CATEGORY` (`ID`);
ALTER TABLE `ITEM` ADD CONSTRAINT `FK_COMPANY_TO_ITEM_1` FOREIGN KEY (`COMPANY_ID`) REFERENCES `COMPANY` (`ID`);

ALTER TABLE `ORDERS` ADD CONSTRAINT `FK_USER_TO_ORDERS_1` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`);
ALTER TABLE `ORDERS` ADD CONSTRAINT `FK_ADDRESS_TO_ORDERS_1` FOREIGN KEY (`ADDRESS_ID`) REFERENCES `ADDRESS` (`ID`);

ALTER TABLE `ORDER_DETAILS` ADD CONSTRAINT `FK_ORDERS_TO_ORDER_DETAILS_1` FOREIGN KEY (`ORDERS_ID`) REFERENCES `ORDERS` (`ID`);
ALTER TABLE `ORDER_DETAILS` ADD CONSTRAINT `FK_ITEM_TO_ORDER_DETAILS_1` FOREIGN KEY (`ITEM_ID`) REFERENCES `ITEM` (`ID`);

ALTER TABLE `RECIPE_ITEM` ADD CONSTRAINT `FK_RECIPE_TO_RECIPE_ITEM_1` FOREIGN KEY (`RECIPE_ID`) REFERENCES `RECIPE` (`ID`);
ALTER TABLE `RECIPE_ITEM` ADD CONSTRAINT `FK_ITEM_TO_RECIPE_ITEM_1` FOREIGN KEY (`ITEM_ID`) REFERENCES `ITEM` (`ID`);

ALTER TABLE `REVIEW` ADD CONSTRAINT `FK_RECIPE_TO_REVIEW_1` FOREIGN KEY (`RECIPE_ID`) REFERENCES `RECIPE` (`ID`);
ALTER TABLE `REVIEW` ADD CONSTRAINT `FK_USER_TO_REVIEW_1` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`);

ALTER TABLE `ADDRESS` ADD CONSTRAINT `FK_USER_TO_ADDRESS_1` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`);


ALTER TABLE `LIVECOMMERCE` ADD CONSTRAINT `FK_LIVECOMMERCE_TO_MANAGER_1` FOREIGN KEY (`MANAGER_ID`) REFERENCES `MANAGER` (`ID`);
ALTER TABLE `LIVECOMMERCE` ADD CONSTRAINT `FK_LIVECOMMERCE_TO_COMPANY_1` FOREIGN KEY (`COMPANY_ID`) REFERENCES `COMPANY` (`ID`);

ALTER TABLE `LIVECOMMERCE_KEYWORD` ADD CONSTRAINT `FK_LIVECOMMERCE_KEYWORD_TO_KEYWORD_1` FOREIGN KEY (`KEYWORD_ID`) REFERENCES `KEYWORD` (`ID`);
ALTER TABLE `LIVECOMMERCE_KEYWORD` ADD CONSTRAINT `FK_LIVECOMMERCE_KEYWORD_TO_LIVECOMMERCE_1` FOREIGN KEY (`LIVECOMMERCE_ID`) REFERENCES `LIVECOMMERCE` (`ID`);

ALTER TABLE `USER_KEYWORD` ADD CONSTRAINT `FK_USER_TO_USER_KEYWORD_1` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`);
ALTER TABLE `USER_KEYWORD` ADD CONSTRAINT `FK_KEYWORD_TO_USER_KEYWORD_1` FOREIGN KEY (`KEYWORD_ID`) REFERENCES `KEYWORD` (`ID`);

ALTER TABLE `RECIPE_KEYWORD` ADD CONSTRAINT `FK_KEYWORD_TO_RECIPE_KEYWORD_1` FOREIGN KEY (`KEYWORD_ID`) REFERENCES `KEYWORD` (`ID`);
ALTER TABLE `RECIPE_KEYWORD` ADD CONSTRAINT `FK_RECIPE_TO_RECIPE_KEYWORD_1` FOREIGN KEY (`RECIPE_ID`) REFERENCES `RECIPE` (`ID`);
